/*******************************************************************************************
* @Name         ClaimaticAuthenticationAPIResponse
* @Author       Convene-tech
* @Date         11/19/2020
* @Group        Claimatic Service
* @Description  This is a wrapper class to store the token.
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0            convene-tech      11/19/2020          Initial Creation                                                      
*******************************************************************************************/

Public class ClaimaticAuthenticationAPIResponse{
    public string token;
    public string email;
}