public class ConstantClass {

public static string CLASSNAME = '';
public static string METHODNAME = '';
public static string ERROR = 'Error';
public static string ERRORTYPE_DML = 'DML';
public static string NULL_VALUE = null;
    
//*********** Account Fields *******************************//
public static string ACCOUNT_OBJECT = 'Account';
public static string ACCOUNT_UPSERT_DATASYNC = 'UpsertAccountSync';    
public static string ACCOUNT_FIELDSET = 'Account_Sync';  
public static string YES_VALUE = 'Yes';
public static string ACCOUNT_ID = 'Id';
public static string ACCOUNT_NPN = 'NPN__c';
public static string ACCOUNT_HIPPOCRMIDENTIFIER = 'Hippo_CRM_Identifier__c';
public static string ACCOUNT_SYNCTOAGENTSYNC = 'Sync_to_AgentSync__c';
    
//*********** Contact Fields *******************************//
public static string CONTACT_OBJECT = 'Contact';
public static string CONTACT_UPSERT_DATASYNC = 'UpsertContactSync';    
public static string CONTACT_FIELDSET = 'Contact_Sync';  
public static string CONTACT_ID = 'Id';
public static string CONTACT_NPN = 'NPN__c';
public static string CONTACT_HIPPOCRMIDENTIFIER = 'Hippo_CRM_Identifier__c';
public static string CONTACT_SYNCTOAGENTSYNC = 'Sync_to_AgentSync__c';

    
}