public class Constants {

    /*--- Declaring Variables ----*/
    
    public static String method = 'method';
    public static String input_type = 'input_type';
    public static String response_type = 'response_type';
    public static String rest_data = 'rest_data';
    public static String input_type_JSON = 'JSON';
    public static String input_type_response_type = 'JSON';
    public static String method_POST = 'POST';
    public static String Content_type = 'application/x-www-form-urlencoded';
    
    
    /*---- Declaring API Methods ----*/
    
    public static String method_Login = 'Login';
    public static String method_Logout = 'Logout';
    public static String method_CreatePaymentMaster = 'CreatePaymentMaster';
    Public static String method_StopPayment = 'StopPayment';
    Public static String method_ResendEmails = 'ResendEmails';
    Public static String method_UpdateProfile = 'UpdateProfile';
    Public static String method_GetPaymentStatus = 'GetPaymentStatus';
    Public static String method_CreateVendor = 'CreateVendor';
    Public static String method_GetDocument = 'GetDocument';
    Public static String method_Paymentfeedback = 'Payment Feedback';
   
    
    /*--- Declaring Variables Using Methods ---*/
    
    public static String PM_PaymentType = 'Vendor';
    public static String PM_DEV = 'Dev';
}